# Yaml configuration file for generating Debian-11 official builds.
trigger: none
schedules:
- cron: "30 18 * * *"
  displayName: Daily Build 12:00 AM IST
  branches:
    include:
    - develop
  always: true

variables:
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)/out
  TESTOUTPUTROOT: $(OUTPUTROOT)/TEST
  OS: 'DEBIAN11-64'
  ONEBRANCH_AME_ACR_LOGIN: cdpx5d0f2841795b49c69ab1c2195fc9a4ea00.azurecr.io
  LinuxContainerImage: 'cdpx5d0f2841795b49c69ab1c2195fc9a4ea00.azurecr.io/official/inmage-azure-siterecovery:debian11_20230406.1'
  CDP_BUILD_TAG: debian11

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    cloudvault:
      enabled: true
      runmode: stage
      artifacts:
        - drop_build_main
    globalSdl:
      tsa:
        enabled: false
      binskim:
        break: false
      policheck:
        break: false

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: linux

        variables:
          ob_outputDirectory: '$(Build.SourcesDirectory)/out'
          ob_linuxSymbolsPublishing_enabled: true
          ob_linuxSymbolsPublishing_symbolsFolder: '$(REPOROOT)/Symbols'

        steps:
          # Download kernel headers.
          - task: Bash@3
            displayName: 'Download Kernel Headers'
            inputs:
              filePath: '$(REPOROOT)/host/drivers/InVolFlt/linux/user_space/build/ubuntu.sh'
              failOnStandardError: true

          # Generate agent build.
          - task: Bash@3
            displayName: 'Generate Agent Build'
            inputs:
              filePath: '$(REPOROOT)/.pipelines/BuildLinuxAgent.sh'
              failOnStandardError: true

          # Generate pushinstallclient tar.
          - task: Bash@3
            displayName: 'Generate Pushinstallclient Tar'
            inputs:
              targetType: 'inline'
              script: |
                cd $(REPOROOT)/host/Linux_x86_64/pushInstallerCli/release
                tar cvzf $(OS)_pushinstallclient.tar.gz pushinstallclient
              failOnStandardError: true

          # Capature symbols for publishing.
          - task: Bash@3
            displayName: 'Capature Symbols For Publishing'
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(REPOROOT)/Symbols
                find $(REPOROOT)/host -name *.dbg -exec cp -f {} $(REPOROOT)/Symbols \;
              failOnStandardError: true

          # Copy build artifacts.
          - task: Bash@3
            displayName: 'Copy Build Artifacts'
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(OUTPUTROOT) $(TESTOUTPUTROOT)
                cp -f $(REPOROOT)/host/Linux_x86_64/setup_ua/release/*.tar.gz $(OUTPUTROOT)
                cp -f $(REPOROOT)/host/Linux_x86_64/pushInstallerCli/release/$(OS)_pushinstallclient.tar.gz $(OUTPUTROOT)
                cp -f $(REPOROOT)/host/*.tar.gz $(OUTPUTROOT)
                cp -f $(REPOROOT)/host/Linux_x86_64/setup_ua/release/supported_kernels $(OUTPUTROOT)/$(OS)_supported_kernels.txt
                cp -f $(REPOROOT)/host/AgentBuild.log $(OUTPUTROOT)/$(OS)_AgentBuild.log
                AGENT_VERSION=`grep -w INMAGE_PRODUCT_VERSION $(REPOROOT)/host/common/version.h | tr ',' '.' | cut -d" " -f3 | tr -d "\n"`
                echo -n ${AGENT_VERSION} > $(REPOROOT)/host/AgentVersion_${AGENT_VERSION}_$(OS).txt
                cp -f $(REPOROOT)/host/AgentVersion*.txt $(OUTPUTROOT)
                cp -f $(REPOROOT)/build/scripts/general/OS_details.sh $(OUTPUTROOT)
                if [ -f $(REPOROOT)/host/Linux_x86_64/tests_test_agent/release/indskflt_ct ]; then
                    cp -f $(REPOROOT)/host/Linux_x86_64/tests_test_agent/release/indskflt_ct $(TESTOUTPUTROOT)
                fi
                cat $(OUTPUTROOT)/AgentVersion*.txt > $(OUTPUTROOT)/Build_details.txt
                echo "" >> $(OUTPUTROOT)/Build_details.txt
                ls $(OUTPUTROOT) | grep -v Build_details.txt >> $(OUTPUTROOT)/Build_details.txt
                openssl version > $(OUTPUTROOT)/openssl.txt
                openssl version -d >> $(OUTPUTROOT)/openssl.txt
                ls -l /etc/ssl/certs/ >> $(OUTPUTROOT)/openssl.txt
              failOnStandardError: true
